import ts from "../assets/icons/ts.svg";
import { AiFillHtml5 } from "react-icons/ai";
import { TbBrandMantine, TbBrandNextjs } from "react-icons/tb";
import { FcLinux } from "react-icons/fc";
import { DiJavascript1 } from "react-icons/di";
import { GiMoon } from "react-icons/gi";
import { BsStripe } from "react-icons/bs";
import {
  SiCanva,
  SiMui,
  SiRedux,
  SiStyledcomponents,
  SiTailwindcss,
  SiMongodb,
  SiExpress,
  SiSocketdotio,
  SiPm2,
  SiPostman,
  SiVercel,
  SiFirebase,
  SiKakaotalk,
} from "react-icons/si";
import {
  FaBootstrap,
  FaCss3,
  FaFigma,
  FaGithub,
  FaReact,
  FaSass,
  FaNodeJs,
  FaDocker,
  FaNpm,
} from "react-icons/fa";

export const education = [
  {
    icon: <AiFillHtml5 />,
    name: "Html",
    color: "#e96228",
    link: "https://www.w3schools.com/html/",
  },
  {
    icon: <FaCss3 />,
    name: "Css",
    color: "#2862e9",
    link: "https://www.w3schools.com/css/",
  },
  {
    icon: <DiJavascript1 />,
    name: "JavaScript",
    color: "#b8b814",
    link: "https://www.w3schools.com/js/",
  },
  {
    url: ts,
    name: "TypeScript",
    color: "#1b95ea",
    link: "https://www.typescriptlang.org/",
  },
  {
    icon: <FaReact />,
    name: "ReactJS",
    color: "#5ed3f3",
    link: "https://react.dev/",
  },
  {
    icon: <FaFigma />,
    name: "Figma",
    color: "#9d56f7",
    link: "https://Figma.com",
  },
  {
    icon: <FaGithub />,
    name: "Github",
    color: "black",
    link: "https://Github.com",
  },
  {
    icon: <SiRedux />,
    name: "Redux",
    color: "#7248b6",
    link: "https://redux-toolkit.js.org/",
  },
  {
    icon: <SiTailwindcss />,
    name: "Tailwind",
    color: "#3fbff8",
    link: "https://Tailwindcss.com",
  },
  {
    icon: <FaSass />,
    name: "SASS",
    color: "#c76494",
    link: "https://sass-lang.com/",
  },
  {
    icon: <FaBootstrap />,
    name: "Bootstrap",
    color: "#7910f2",
    link: "https://getbootstrap.com/",
  },
  {
    icon: <TbBrandMantine />,
    name: "Mantine",
    color: "#339af0",
    link: "https://mantine.dev/",
  },
  {
    icon: <SiStyledcomponents />,
    name: "Styled Components",
    width: "16px",
    color: "#d4abb1",
    link: "https://styled-components.com",
  },
  {
    icon: <SiCanva />,
    name: "Canva",
    color: "#3077e1",
    link: "https://Canva.com",
  },
  {
    icon: <SiMui />,
    name: "Material UI",
    width: "20px",
    color: "#0883ff",
    link: "https://mui.com/",
  },
  {
    icon: <FaNodeJs />,
    name: "Node Js",
    width: "20px",
    color: "#46cb18",
    link: "https://nodejs.org/en",
  },
  {
    icon: <SiMongodb />,
    name: "MongoDB",
    width: "18px",
    color: "#3f9422",
    link: "https://account.mongodb.com/account/login",
  },
  {
    icon: <TbBrandNextjs />,
    name: "Next Js",
    width: "20px",
    color: "#141414",
    link: "https://nextjs.org/",
  },
  {
    icon: <SiExpress />,
    name: "Express Js",
    width: "20px",
    color: "#999999",
    link: "https://expressjs.com/",
  },
  {
    icon: <FaDocker />,
    name: "Docker",
    width: "20px",
    color: "#0077d2",
    link: "https://www.docker.com/",
  },
  {
    icon: <FaNpm />,
    name: "Npm",
    width: "25px",
    color: "#ff5349",
    link: "https://www.npmjs.com/",
  },
  {
    icon: <SiSocketdotio color="black" />,
    name: "Socket.io",
    width: "25px",
    color: "#ececec",
    link: "https://socket.io/",
  },
  {
    icon: <SiPm2 />,
    name: "PM2",
    width: "25px",
    color: "#00d2c0",
    link: "https://pm2.keymetrics.io/",
  },
  {
    icon: <FcLinux />,
    name: "Linux",
    width: "25px",
    color: "#f2f27a",
    link: "https://www.kernel.org/",
  },
  {
    icon: <SiPostman />,
    name: "Postman",
    width: "20px",
    color: "#ff8c00",
    link: "https://www.postman.com/",
  },
  {
    icon: <GiMoon />,
    name: "Moon Modeler",
    width: "20px",
    color: "#010203",
    link: "https://www.datensen.com/data-modeling/moon-modeler-for-databases.html",
  },
  {
    icon: <SiVercel />,
    name: "Vercel",
    width: "20px",
    color: "#100c08",
    link: "https://vercel.com/",
  },
  {
    icon: <SiFirebase />,
    name: "Firebase",
    width: "20px",
    color: "#ff8936",
    link: "https://console.firebase.google.com/",
  },
  {
    icon: <BsStripe />,
    name: "Stripe",
    width: "20px",
    color: "#861d86",
    link: "https://stripe.com/",
  },
  {
    icon: <SiKakaotalk />,
    name: "Kakao Developers",
    width: "16px",
    color: "#000080",
    link: "https://developers.kakao.com/",
  },
];
